export const designProjects = [
  {
    id: "hotel-3x3-grid",
    title: "Hotel Compare 3x3",
    type: "LP Archive",
    status: "Local",
    url: "/archive/3x3-grid/index.html",
    localPath: "C:\\Users\\yuki1\\OneDrive\\ドキュメント\\統合サイト",
    image: "/images/hotel-shuffle-fv.png",
    accent: "gold",
    description:
      "HOTEL SHUFFLE と HOTEL REFRAIN を3x3グリッドで比較する、統合サイト内のLPデザイン案。",
    tags: ["Landing Page", "Hotel", "Archive"],
  },
  {
    id: "hotel-shuffle",
    title: "HOTEL SHUFFLE",
    type: "Official HP",
    status: "Published",
    url: "https://hotelshuffle.com/",
    localPath: "C:\\Users\\yuki1\\OneDrive\\ドキュメント\\Hotel Shuffle HP",
    image: "/showcase/hotel-shuffle.png",
    accent: "gold",
    description:
      "池袋のホテル公式サイト。重厚感のある黒とゴールドを軸に、客室写真と予約導線を前面に出した構成。",
    tags: ["Hotel", "Next.js", "Responsive"],
  },
  {
    id: "hotel-refrain",
    title: "HOTEL REFRAIN",
    type: "Official HP",
    status: "Published",
    url: "https://www.hotelrefrain.com/",
    localPath: "C:\\Users\\yuki1\\OneDrive\\ドキュメント\\Hotel refrainHP",
    image: "/showcase/hotel-refrain.png",
    accent: "rose",
    description:
      "池袋のホテル公式サイト。明るく親しみやすいトーンで、客室・お知らせ・予約導線を整理。",
    tags: ["Hotel", "Next.js", "Content"],
  },
  {
    id: "work-shift",
    title: "WORK SHIFT INC.",
    type: "Corporate HP",
    status: "Published",
    url: "https://www.work-shift.co.jp/",
    localPath: "C:\\Users\\yuki1\\OneDrive\\ドキュメント\\WORK SHIFT INC",
    image: "/showcase/work-shift.png",
    accent: "blue",
    description:
      "企業サイト。事業内容と問い合わせ導線をすぐ把握できる、落ち着いたコーポレートデザイン。",
    tags: ["Corporate", "Next.js", "Business"],
  },
  {
    id: "hotel-integrated-3x3",
    title: "HOTEL SHUFFLE / REFRAIN 3×3",
    type: "Integrated LP",
    status: "Draft",
    url: "/hotel-integrated-3x3",
    localPath: "C:\\Users\\yuki1\\OneDrive\\ドキュメント\\統合サイト\\app\\3x3-grid",
    image: "/images/hotel-shuffle-fv.png",
    accent: "gold",
    description:
      "HOTEL SHUFFLEとHOTEL REFRAINを、9マスのグリッドで比較できる統合サイト。雰囲気、客室、予約導線をファーストビューに集約。",
    tags: ["Hotel", "3x3 Grid", "Integrated"],
  },
];
